stages:
  - build
  - test

maven-build:
  tags:
    - AutoTest1
  stage: build
  script: "mvn compile"

run-test:
  tags:
    - AutoTest1
  stage: test
  script: "mvn clean test -DsuiteXmlFile=configs/config-gitlab.xml -Dsurefire.rerunFailingTestsCount=2"
